---
title: "Kobe Logistic Splines"
output: html_notebook
---

```{r}
library(dplyr)     # for data wrangling
library(ggplot2)   # for awesome plotting

# Modeling packages
library(earth)     # for fitting MARS models
library(caret)     # for automating the tuning process

# Model interpretability packages
library(vip)       # for variable importance
library(pdp)       # for variable relationships

library(tidyverse)
library(mlbench)
```

```{r}
kobeData <- read.csv('kobe_data.csv');
kobeData  <-na.omit(kobeData);

# Parse Game date into Years 
kobeData$Year <- format(as.Date(kobeData$game_date, format="%Y"),"%Y")
kobeData$Year <- floor(as.numeric(kobeData$Year))

# Remove columns we dont need
kobeData<- subset(kobeData, select=c(-game_date,-game_id,-team_id,-team_name,-matchup,-opponent, -season))
head(kobeData)
```
Use Carats to make the data into dummies
```{r}
dmy <- dummyVars("~ . ",data = kobeData)
trsf <- data.frame(predict(dmy, newdata = kobeData))
print(trsf)
```

Construct testing and training sets 
```{r}
training.samples <- kobeData$shot_made_flag %>% 
  createDataPartition(p = 0.8, list = FALSE)
train.data  <- kobeData[training.samples, ]
test.data <- kobeData[-training.samples, ]
```

Change the variables from categorical to dummy variables
```{r}
# Dummy code categorical predictor variables
x <- model.matrix(shot_made_flag~., train.data)[,-1]
# Convert the outcome (class) to a numerical variable, set pos as 1, neg as 0 
y <- train.data$shot_made_flag
```
Make the Logistic Spline Model
```{r}
marsModel <- earth(
   shot_made_flag~ .,  
  data = train.data   
)

# Print model summary
print(marsModel)
```
Coeefficients 
```{r}
summary(marsModel) %>% .$coefficients %>% head(10)
```

```{r}
plot(marsModel, which = 1)
```
```{r}
# Tuning
hyper_grid <- expand.grid(
  degree = 1:3, 
  nprune = seq(2, 100, length.out = 10) %>% floor()
)
head(hyper_grid)

# Cross-validated model
set.seed(123)  # for reproducibility
cv_mars <- train(
  x = subset(train.data, select = -shot_made_flag),
  y = as.factor(train.data$shot_made_flag),
  method = "earth",
  trControl = trainControl(method = "cv", number = 10),
  tuneGrid = hyper_grid
)

# View results
cv_mars$bestTune
##    nprune degree
## 25     45      3
ggplot(cv_mars)
```
Variable Importance
```{r}
p1 <- vip(cv_mars, num_features = 40, bar = FALSE, value = "gcv") + ggtitle("GCV")
p2 <- vip(cv_mars, num_features = 40, bar = FALSE, value = "rss") + ggtitle("RSS")
gridExtra::grid.arrange(p1, p2, ncol = 2)
```
Checking Misc Rate 
```{r}
predictedLabels <- predict(cv_mars, test.data)
# get num of data points in test set
sizeTestSet = dim(test.data)[1]

# get # of data points that are misclassified
error = sum(predictedLabels != test.data$shot_made_flag)

# calculate misclassification rate
misclassificationRate = error / sizeTestSet

# display misclassification rate
print(misclassificationRate)
```

